config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get '/home/about' => 'homes#about'

  resources :users, only: [:show, :edit, :update, :index]
  resources :books

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  attachment :profile_image

  validates :name, presence: true
  validates :name, length: { in: 2..20 }
  validates :name, uniqueness: true
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    added_attrs = [:name, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def index
     @book = Book.new
     @books = Book.all
     @user = User.find(current_user.id)
  end


  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice]="Book was successfully created."
      redirect_to book_path(Book.last.id.to_s)
    else
      @user = User.find(current_user.id)
      @books = Book.all
      render :index
    end
  end


  def show
    @book = Book.new
    @books = Book.find(params[:id])
    @user = User.find(@books.user_id)
  end


  def edit
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end


  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice]="Book was successfully destroyed."
    redirect_to books_path
  end


  def update
     @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice]="Book was successfully updated."
      redirect_to book_path(params[:id])
    else
      render :edit
    end
  end


  private
  def book_params
    params.require(:book).permit(:title,:body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @book = Book.new
    @user = User.find(current_user.id)
    @users = User.all
  end


  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = Book.where(user_id: @user.id)
  end


  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end


  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="User was successfully updated."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end


  private
  def user_params
    params.require(:user).permit(:name,:introduction,:profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_new.html.erb
<h2>New book</h2> 
   
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:<br>

  <% @book.errors.full_messages.each do |message| %>
    <br>■<%= message %>
  <% end %> 
<% end %>  

<%= form_with model:@book, local:true do |f| %> 

  <input name="utf8" type="hidden" value="✓">
  <div class="form-group">
    <label for="book_title">Title</label>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit 'Create Book', class: 'btn btn-success' %>
  </div>

<% end %>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto"> 

      <h1>Editing Book</h1>   

      <% if @book.errors.any? %>     
        <%= @book.errors.count %>errors prohibited this book from being saved:<br>

        <% @book.errors.full_messages.each do |message| %>      
          <br>■<%= message %>  
        <% end %>
      <% end %> 

      <%= form_with model:@book, local:true do |f| %>     

        <input name="utf8" type="hidden" value="✓">    
        <div class="form-group"> 
          <label for="book_title">Title</label>
          <%= f.text_field :title, class: 'form-control' %>      
        </div> 

        <div class="form-group">  
          <%= f.text_area :body, class: 'form-control' %>   
        </div> 

        <div class="form-group">
          <%= f.submit 'Update Book', class: 'btn btn-success' %>
        </div>

      <% end %>

      <a class="edit" href="/books/<%= @book.id %>">Show</a> |
      <a class="back" href="/books">Back</a> 

    </div>
  </div>
</div>

app/views/books/index.html.erb
  <div class='container px-5 px-sm-0'>
    <div class='row'>

      <div class='col-md-3'>

        <%= render 'users/info', user: @user %>

        <%= render 'books/new', books: @books %>

      </div>

      <div class='col-md-8 offset-md-1'>

        <h2>Books</h2>

        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user_id) do %>
                    <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
                  <% end %>
                </td>
                <td><%= link_to book.title, book_path(book.id) %></td>
                <td><%= book.body %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

app/views/books/show.html.erb
  <div class='container px-5 px-sm-0'>
    <div class='row'>

      <div class='col-md-3'>

        <%= render 'users/info', user: @user %>

        <%= render 'books/new', books: @books %>

      </div>

      <div class='col-md-8 offset-md-1'>

        <h2>Book detail</h2>

        <table class='table table-hover table-inverse'>
          <thead>
          </thead>
          <tbody>
            <tr>
              <td>
                <%= attachment_image_tag @books.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %><br>
                <%= link_to @user.name, user_path(@user.id) %>
              </td>
              <td><%= link_to @books.title, book_path(@books.id) %></td>
              <td><%= @books.body %></td>
              <% if @user.id == current_user.id %>
                <td><%= link_to "Edit", edit_book_path(@books.id), class: 'btn btn-sm btn-success' %></td>
                <td><%= link_to "Destroy", "/books/#{@books.id}", method: :delete, data: {confirm:"本当に消しますか？"}, class: 'btn btn-sm btn-danger' %></td>
              <% end %>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>

app/views/homes/about.html.erb
<p id="notice"></p>
<div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<p id="notice"></p>

<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/06cab59cbd.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

              <% if user_signed_in? %>
                <li><%= link_to " Home", user_path(current_user.id), {class: "fas fa-home nav-link text-light"} %></li>
                <li><%= link_to " Users", "/users", {class: "fas fa-users nav-link text-light"} %></li>
                <li><%= link_to " Books", "/books", {class: "fas fa-book-open nav-link text-light"} %></li>
                <li><%= link_to " logout", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" %></li>
              <% else %>
                <li><%= link_to " Home", "/", {class: "fas fa-home nav-link text-light"} %></li>
                <li><%= link_to " About", "/home/about", {class: "fas fa-link nav-link text-light"} %></li>
                <li><%= link_to " sign up", new_user_registration_path, {class: "fas fa-user-plus nav-link text-light"} %></li>
                <li><%= link_to " login", new_user_session_path, {class: "fas fa-sign-in-alt nav-link text-light"} %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <p id="notice">
      <%= flash[:notice]%>
    </p>

    <%= yield %>

    <footer>
      <div class='container mt-5'>
  	    <div class='row'>
    	    <div class='mx-auto'>
    		    <p>CopyRight Infratop.inc</p>
        	</div>
        </div>
      </div>
    </footer>

  </body>

</html>

app/views/users/_info.html.erb
<h2>User info</h2>

<table class='table'>
  <tr>
    <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %>
  </tr>
  <tr>
	  <th>name</th>
	  <th><%= @user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= @user.introduction %></th>
  </tr>
</table>

<div class='row'>
  <%= link_to edit_user_path(@user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <h2>User info</h2>

      <% if @user.errors.any? %>
        <%= @user.errors.count %>errors prohibited this user from being saved:<br>
        <% @user.errors.full_messages.each do |message| %>
          <br>■<%= message %>
        <% end %>
      <% end %>

      <%= form_with model:@user, local:true do |f| %>

        <div class="form-group">
          <label for="user_name">Name</label>
          <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前", class: 'form-control' %>
        </div>
        <div class="form-group">
          <label for="user_image">Image</label>
          <%= f.attachment_field :profile_image, class: 'form-control-file' %>
        </div>
        <div class="form-group">
          <label for="user_introduction">Introduction</label>
          <%= f.text_area :introduction, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class: 'btn btn-secondary' %>
        </div>

      <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>

    <div class='col-md-3'>

      <%= render 'users/info', user: @user %>

      <%= render 'books/new', books: @books %>

    </div>

    <div class='col-md-8 offset-md-1'>

      <h2>Users</h2>

      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>

  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>

    <div class='col-md-3'>

      <%= render 'users/info', user: @user %>

      <%= render 'books/new', books: @books %>

    </div>

    <div class='col-md-8 offset-md-1'>

      <h2>Books</h2>

      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user_id) do %>
                  <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>